Controllers/ProductiwarehauseController.cs
//using AspNetCore;
//using Microsoft.AspNetCore.Mvc;
//using partner_aluro.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using partner_aluro.ViewModels;
using partner_aluro.Models;
using partner_aluro.Services.Interfaces;
using Microsoft.AspNetCore.Mvc.Rendering;
using static partner_aluro.Core.Constants;
using partner_aluro.Services;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace partner_aluro.Controllers
{
    [Authorize]
    public class ProductiwarehauseController : Controller
    {
        private readonly IUnitOfWorkProduct _unitOfWorkProduct;
        private readonly IProductService _warehouseService;
        public ProductiwarehauseController(IProductService warehauseService, IUnitOfWorkProduct unitOfWorkProduct)
        {
            _warehouseService = warehauseService;
            _unitOfWorkProduct = unitOfWorkProduct;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var produkt = _warehouseService.GetProductId(id);

            var ListaKategorii = _warehouseService.GetCategory();
            var categoryList = _warehouseService.GetCategory().ToList();

            var roleItems = ListaKategorii.Select(cat =>
                new SelectListItem(
                    cat.Name,
                    cat.Description
                    )).ToList();

            var vm = new AddProductFormModel
            {
                Product = produkt,
                Categories = roleItems,
            };


            return View(vm);
        }

        [HttpPost]
        public IActionResult EditOnPost(AddProductFormModel dataProduct)
        {
            var produkt = _unitOfWorkProduct.Product.GetProductId(dataProduct.Product.ProductId);


            produkt.Name = dataProduct.Product.Name;
            produkt.Symbol = dataProduct.Product.Symbol;
            produkt.Description = dataProduct.Product.Description;
            produkt.CenaProduktu = dataProduct.Product.CenaProduktu;
            produkt.CenaProduktuDetal = dataProduct.Product.CenaProduktuDetal;
            produkt.WagaProduktu = dataProduct.Product.WagaProduktu;
            produkt.SzerokoscProduktu = dataProduct.Product.SzerokoscProduktu;
            produkt.WysokoscProduktu = dataProduct.Product.WysokoscProduktu;
            produkt.GlebokoscProduktu = dataProduct.Product.WagaProduktu;
            produkt.Bestseller = dataProduct.Product.Bestseller;
            produkt.Ukryty = dataProduct.Product.Ukryty;

            _unitOfWorkProduct.Product.UpdateProduct(produkt);


            return RedirectToAction("List");
        }
        [HttpGet]
        public IActionResult Add()
        {

            var ListaKategorii = _warehouseService.GetCategory();
            var categoryList = _warehouseService.GetCategory().ToList();

            var roleItems = ListaKategorii.Select(cat =>
                new SelectListItem(
                    cat.Name,
                    cat.Description
                    )).ToList();

            var vm = new AddProductFormModel
            {
                Categories = roleItems
            };


            return View(vm);
        }

        [HttpPost]
        public IActionResult Add(AddProductFormModel addProductModel)
        {
            Product produkt = addProductModel.Product;
            produkt.DataDodania = DateTime.Now;

            produkt.Ukryty = false;
            produkt.Bestseller = true;

            var ListaKategorii = _warehouseService.GetCategory();

            string text;
            int idCatSelected =0;

            foreach (var categoris in addProductModel.Categories)
            {
                if (categoris.Selected == true)
                {
                    text = categoris.Text;
                    foreach (var listAllCat in ListaKategorii)
                    {
                        if (listAllCat.Name == text)
                        {
                            idCatSelected = listAllCat.CategoryId;
                        }
                    }

                }
            }
            if (idCatSelected != 0)
            {
                produkt.CategoryId = idCatSelected;
            }

            addProductModel.Product = produkt;
            ModelState.Remove("Product.ProductId");
            if (!ModelState.IsValid)
            {

                return View(addProductModel);
            }

            if (produkt != null)
            {
                var id = _warehouseService.AddProduct(produkt); //wazne aby przypisac
            }

            return RedirectToAction("List");

        }

        [HttpGet]
        public IActionResult List()
        {
            var produkty = _warehouseService.GetProductList();

            return View(produkty);
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            var product = _warehouseService.GetProductId(id);
            return View(product);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            _warehouseService.DeleteProductId(id);
            return RedirectToAction("List");
        }
    }
}

Views/Productiwarehause/Add.cshtml
@model partner_aluro.ViewModels.AddProductFormModel

@{
    ViewData["Title"] = "Dodaj produkt";
    Layout = "~/Views/Shared/_Dashboard.cshtml";
}

@using (Html.BeginForm("Add", "Productiwarehause", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.HiddenFor(h=>Model.Product.ProductId)
    @*@Html.ValidationSummary()*@
    @Html.Partial("_FormProduct")
    <button type="submit">Dodaj produkt</button>
}

Views/Productiwarehause/Details.cshtml
@model partner_aluro.Models.Product
<!-- Product section-->
<section class="py-2">
    <div class="container px-2 px-lg-3 my-3">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="https://dummyimage.com/600x700/dee2e6/6c757d.jpg" alt="..." /></div>
            <div class="col-md-6">
                <div class="small mb-1">Symbol: @Model.Symbol</div>
                    <h1 class="display-5 fw-bolder">@Model.Name</h1>
                <div class="fs-5 mb-5">
                    <span class="text-decoration-line-through">Cena detaliczna: @Model.CenaProduktuDetal</span>
                    <span>Cena produkTu: @Model.CenaProduktu</span>
                </div>
                <p class="lead">@Model.Description</p>
                <p class="lead">Wymiary: @Model.SzerokoscProduktu Wys: @Model.SzerokoscProduktu, Glebokosc:@Model.GlebokoscProduktu </p>
                <div class="d-flex">
                    Ilość: <input class="form-control text-center me-3" id="inputQuantity" type="num" value="1" style="max-width: 3rem" />
                    <a asp-controller="Cart" asp-action="AddToCart" asp-route-id="@Model.ProductId" class="btn btnalert-primary ">Dodaj do zamowienia</a>
                    @*<button asp-action="DodajDoKoszyka" asp-controller="Koszyk" asp-route-id="@Model.ProductId" class="btn btn-outline-dark flex-shrink-0" type="button">
                        <i class="bi-cart-fill me-1"></i>
                        Dodaj do zamówienia
                    </button>*@
                </div>
            </div>
        </div>
    </div>
</section>

Views/Productiwarehause/List.cshtml
@{
    ViewData["Title"] = "Lista produktów wybranej Kategorii";
    Layout = "~/Views/Shared/_Dashboard.cshtml";
}


@model IEnumerable<partner_aluro.Models.Product>

@*
@model partner_aluro.ViewModels.AddProductFormModel
*@
<h1>Lista produktów</h1>
<div class="text-center">
    <h1 class="display-4">Lista produktów</h1>
    
    <a asp-controller="Productiwarehause" asp-action="Add" class="btn btn-success" px-3">
    Dodaj produkt
    </a>


    @if 
    (
        @Model != null && @Model.Any()
    )
    {
        <div class="row">
            <div class="col-md-12 mb-3">
                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table id="example"
                               class="table table-striped data-table"
                               style="width: 100%">
                                <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Symbol</th>
                                        <th>Nazwa produktu</th>
                                        <th>Cena produktu</th>
                                        <th>Cena sprzedazy</th>
                                        <th>Opis produktu</th>
                                        <th>Kategoria</th>
                                        <th>Edit</th>
                                        <th>Usuń</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var productFormModel in Model)
                                    {
                                        <tr>
                                            <td>@productFormModel.ProductId</td>
                                            <td>@productFormModel.Symbol</td>
                                            <td>@productFormModel.Name</td>
                                            <td>@productFormModel.CenaProduktu</td>
                                            <td>@productFormModel.CenaProduktuDetal</td>
                                            <td>@productFormModel.Description</td>
                                            <td>@productFormModel.CategoryId</td>
                                            <td>
                                                <a asp-controller="Productiwarehause" asp-action="Edit" asp-route-id="@productFormModel.ProductId">Edit</a>
                                            </td>
                                            <td>
                                                <a asp-controller="Productiwarehause" asp-action="Delete" asp-route-id="@productFormModel.ProductId">Usuń</a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th scope="col">Id</th>
                                        <th scope="col">Symbol</th>
                                        <th scope="col">Nazwa produktu</th>
                                        <th scope="col">Cena produktu</th>
                                        <th scope="col">Cena sprzedazy</th>
                                        <th scope="col">Opis</th>
                                        <th scope="col">Kategoria</th>
                                        <th scope="col">Edytuj</th>
                                        <th scope="col">Usuń</th>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    }

</div>

@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@